name: Sync Image to Aliyun  Example
# Mysql 8.0.35
# skopeo copy docker://docker.io/mysql:8.0.35 docker://registry.cn-guangzhou.aliyuncs.com/you2024/mysql:8.0.35
#  skopeo copy docker://docker.io/redis:7.0.15 docker://registry.cn-guangzhou.aliyuncs.com/you2024/redis:7.0.15
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-guangzhou.aliyuncs.com
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/canal/canal-server:v1.1.7 docker://registry.cn-guangzhou.aliyuncs.com/you2024/canal-server:v1.1.7
         
         
